# Generated by Django 3.0.6 on 2020-05-14 14:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200507_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('pub_date__month',)),
        ),
    ]
