# Generated by Django 3.0.6 on 2020-05-15 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200515_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 3, 7, 50, 748810, tzinfo=utc), editable=False),
        ),
    ]
