# Generated by Django 3.0.6 on 2020-05-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20200519_1805'),
        ('post', '0023_auto_20200519_1500'),
    ]

    operations = [
    ]
