# Generated by Django 3.0.6 on 2020-06-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_file',
            new_name='img_file',
        ),
    ]
