# Generated by Django 3.0.6 on 2020-06-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_auto_20200610_1437'),
    ]

    operations = [
    ]
